name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:  
      - master
      - pipeline

stages:
- stage: build
  jobs:
  - job:
    pool:
      vmImage: windows-latest
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        arguments: '-c Release'
        publishWebProjects: true
        zipAfterPublish: true
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: bin/release/netcoreapp3.1/publish/
        archiveType: zip
        archiveFile: $(Pipeline.Workspace)/webapp.zip
    - publish: $(Pipeline.Workspace)/webapp.zip
      artifact: app 
- stage: deploy
  jobs:
  - deployment:
    environment: dev
    pool:
      vmImage: windows-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: AzureRM
              azureSubscription: 'webapp publish profile'
              WebAppKind: webApp
              WebAppName: mjgweb
